name: build
on: [push, pull_request]

jobs:
  lint:
    strategy:
      matrix:
        wd: [cmd/authenticator, cmd/synchronizer, cmd/token-renewer]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker://golangci/golangci-lint:v1.31.0
      with:
        args: golangci-lint run
      env:
        CGO_ENABLED: 0
  test:
    strategy:
      matrix:
        wd: [cmd/authenticator, cmd/synchronizer, cmd/token-renewer]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: 1.15
    - name: Test build
      working-directory: ${{ matrix.wd }} 
      run: |
        go build -o testbuild && rm testbuild
